# -*- coding: utf-8 -*-
import environ
env = environ.Env()

if env.str('PIPELINE') == 'production':
        pass
#  SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#  SECURE_SSL_REDIRECT = True
#  SESSION_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", True)
#  CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", True)

#  SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'

        





# CSRF_COOKIE_AGE = env.int("DJANGO_CSRF_COOKIE_AGE", 60 * 60 * 24 * 365)
# CSRF_COOKIE_DOMAIN = env("DJANGO_CSRF_COOKIE_DOMAIN", None)
# CSRF_COOKIE_HTTPONLY = env.bool("DJANGO_CSRF_COOKIE_HTTPONLY", False)
# CSRF_COOKIE_NAME = env("DJANGO_CSRF_COOKIE_NAME", "csrftoken")
# CSRF_COOKIE_PATH = env("DJANGO_CSRF_COOKIE_PATH", "/")
# CSRF_COOKIE_SAMESITE = env("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
# CSRF_USE_SESSIONS = env.bool("DJANGO_CSRF_USE_SESSIONS", False)
# CSRF_FAILURE_VIEW = env("DJANGO_CSRF_FAILURE_VIEW", "django.views.csrf.csrf_failure")
# CSRF_HEADER_NAME = env("DJANGO_CSRF_HEADER_NAME", "HTTP_X_CSRFTOKEN")
# CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", [])
